#!/bin/bash
if [[ $# -ne 2 ]]
then 
	echo "An error occurred:you did not pass exactly two arguments" >&2
	exit 1
elif [[ $1 == $2 ]]
then 
	echo "An error occurred:you passed two same arguments" >&2
	exit 1
elif [[ $1 -lt $2 ]]
then 
	echo "$1"
	exit 0
elif [[ $2 -lt $1 ]]
then 
	echo "$2"
	exit 0
else
	echo "An unknown error occurred" >&2
	exit 1
fi
